mobile hamburger menu
usergoodness/usergoodness.github.io pull request #61
Opened 2018-01-25 03:34 UTC by kevikramer

restyled header and created mobile menu hamburger

2018-01-25 03:35 UTC, kevikramer commented
@timbroadwater for the life of me I haven't been able to merge anything into master. Not sure what's going on, nothing turning up on the web. :( Can you help?

2018-01-26 14:49 UTC, michaelschofield submitted a review, later dismissed

2018-01-26 15:58 UTC, timbroadwater commented
@kevikramer sorry, the repos are setup for another to approve.

2018-01-26 16:00 UTC, timbroadwater requested changes
THe changes need to be made to the scss file, otherwise when the SCSS is exported to CSS, this gets overwritten.

2018-01-29 13:23 UTC, closed without merging